# For the Dataset
TEXT_PATH="Dataset\\TR2EN.txt"

# For data clip
START_RANGE=0
STOP_RANGE=1000

# FOR DATA PREPROCESSING
LANGUAGE="english"
START_SYMBOL="<SOS>"
STOP_SYMBOL="<EOS>"
PAD_SYMBOL="<PAD>"
MASK_SYMBOL="[MASK]"
SEPERATE_SYMBOL="[SEP]"
TRESHOLD_LEN_INPUT=785
TRESHOLD_LEN_OUTPUT=50

# FOR RANDOM SPLIT
VALID_RANGE=0.2

# For the Checkpoint
PRETRAIN_CALLBACKS_PATH="pretrain_bart_checkpoint.pth.tar"
FINETUNE_CALLBACKS_PATH="finetune_bart_checkpoint.pth.tar"
LOAD_CALLBACKS_PRETRAIN=False
LOAD_CALLBACKS_FINETUNE=False

# For The Training
PRE_TRAIN=True
FINE_TUNE=True
EPOCHS_PRETRAIN=3
EPOCH_FINETUNE=3
BATCH_SIZE=128
LEARNING_RATE=0.001
BETAS=(0.9,0.98)
EPSILON=(1e-09)

# For The Model
D_MODEL=768
NUM_HEADS=8
PAD_IDX=0
MASKING_VALUE=-1e8
NX=8

# FOR TEST
TEST=True

# FOR PREDICTION
PREDICTION=True
PREDICTION_SENTENCE="Merhaba"




